# This is your workflow file, either `codecov.yaml` or `docker.yaml`
name: Run Tests and Upload Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov kaggle

      # Copy kaggle.json to the required location for Kaggle API authentication
      - name: Setup Kaggle Authentication
        run: |
          mkdir -p ~/.kaggle
          cp ./kaggle.json ~/.kaggle/kaggle.json  # Change path to ./kaggle.json if it's in the root directory
          chmod 600 ~/.kaggle/kaggle.json

      # Set PYTHONPATH to include the src directory
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      # Run tests and generate coverage report
      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml

      # Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Use a secret token to authenticate
          files: ./coverage.xml                # Path to the coverage report
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
